FROM node:18-alpine

# Set working directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Copy app source
COPY . .

# Create non-root user
RUN addgroup -g 1001 -S nodejs
RUN adduser -S alter8 -u 1001

# Change ownership of the working directory
RUN chown -R alter8:nodejs /app
USER alter8

# Expose port
EXPOSE 8000

# Start the application in development mode
CMD ["npm", "run", "dev"]
